### ISSUE TITLE
Add support for built-in sets?

### ISSUE THREAD

**Issue by Cloudperry** [Vindaar/flatBuffers#1]
I'm using this library for a small personal project and it serializes everything I want to except for built-in sets. Flatty also seemed to break (not compile) with built-in sets even though its code seemingly tries to do something with them. For example something like this won't compile:

```nim
import std/[strformat, os]
import pkg/flatBuffers

type
  FileWithPerms* = object
    path*: string
    permissions*: set[FilePermission]

const testFile = FileWithPerms(
  path: "/a/file",
  permissions: {fpUserRead, fpUserWrite},
)

proc flatbufRead[T](path: string): T =
  let buf = readFile(path).fromString
  result = flatTo[T](buf)

asFlat(testFile).writeBuffer("flatbuf-file.bin")
let flatbufFile = flatbufRead[FileWithPerms]("flatbuf-meta.bin")
echo fmt"File is {flatbufFile} after write/read"
``` 

Built-in sets should be easy to handle as they are basically just a big array of bytes under the hood. They also support copyMem. However my quick attempt at adding them to this library didn't work out, because I didn't find a way to get their base type. Maybe I should try adding them again, because copying them is easy and I found out some new things.

```nim
nim> var b: set[uint16]
nim> b.incl 65535
nim> b.incl 20000
nim> b.incl 20001
nim> b.incl 42184
nim> b.incl 12330
nim> b
{12330, 20000, 20001, 42184, 65535} == type set[uint16]
nim> sizeof b
8192 == type int
nim> var c: set[uint16]
nim> copyMem(c.addr, b.addr, 8192)
nim> c
{122, 12330, 20000, 20001, 42184, 65535} == type set[uint16]
```

**Comment by Vindaar** [comment]
Hey! Cool to hear that someone else is using the library. Guess I need to add CI to the repo. :)

I think you're still on version `v0.1.3` or before. I've added support for builtin `set` in `v0.1.4`. In addition there is now a `saveBuffer` / `loadBuffer` convenience helper, which can replace the `flatbufRead` and `asFlat` -> `writeBuffer` calls in your example. So on current master your snippet runs fine (except the file name is different in the write and read calls, but I guess that's a typo / bug left over from simplifying).

Simplified the code now can be:

```nim
import std/[strformat, os]
import pkg/flatBuffers

type
  FileWithPerms* = object
    path*: string
    permissions*: set[FilePermission]

const testFile = FileWithPerms(
  path: "/a/file",
  permissions: {fpUserRead, fpUserWrite},
)

testFile.saveBuffer("flatbuf-file.bin")
let flatbufFile = loadBuffer[FileWithPerms]("flatbuf-file.bin")
echo fmt"File is {flatbufFile} after write/read"
```

Feel free to reopen if there's still an issue!

**Comment by Cloudperry** [comment]
Ok now I see the sets commit. I was testing before 0.1.4 was tagged. The sets serialization now works. No need to do CI, because you already have tests and it will just be extra maintenance effort.

There is one optimization that could make serialization/deserialization a lot faster with sets that are not very sparse. It would be much faster to get the size of the set in bytes and copy it into the buffer. The downside of copying would be a much larger serialized size. Element by element iteration is pretty slow with sets, because internally it goes over the entire array of bytes bit by bit (using bitshifts) and it also does branching on each iteration. I don't need this "fast serialization" though and even Flatty does it element by element.

**Comment by Vindaar** [comment]
You raise a good point about the element-wise vs `copyMem` approach for inbuilt sets. I would normally assume that sets are sparse more often than not. But that might be my personal bias.

I'm considering to add a CT option to decide between the two ways. I would add an extra byte to indicate whether it's packed or 'full' as a prefix to be able to decode which way the data is stored. Could be useful for certain use cases.

**Comment by Vindaar** [comment]
Ok, just ended up doing that. 

We now have a `-d:FullSets=true/false` option to choose the behavior of how sets are stored. That "unfortunately" means the code now is not backward compatible with data files stored before, but I don't imagine you're using it in any such way (just want to mention it).

The default is the old behavior to save space. But users who want the performance can compile with `-d:FullSets=true` to just copy the entire set memory. Note that loading a buffer is independent of the option, because we do use one more byte to indicate the way the set is stored.

edit:
Ahh, I also added an example of the type of data I use it for: 

https://github.com/Vindaar/flatBuffers/blob/master/tests/tMcmcLimit.nim

(just to show that at this point it can really (de)serialize some rather ugly Nim types)

**Comment by c-blake** [comment]
> Element by element iteration is pretty slow with sets, because internally it goes over the entire array

This is true.  For sparse sets there is one simple trick one can do which is have a multi-layer structure called an [aggregate bit vector](http://publications.csail.mit.edu/lcs/pubs/pdf/MIT-LCS-TM-637.pdf) which stores a '1' if any of a block of 32|64-bits is 1, else a 0.  So, you can loop 32|64 bits at a time.  But you can repeat the trick on the "index" layer to index it as well as many times as you like.
